// Render the two boards (time, memory), ranked, best entry per stack.
//   node board.mjs        -> terminal
//   node board.mjs --md   -> also writes LEADERBOARD.md (the live leaderboard)
import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const writeMd = process.argv.includes('--md');

function load(file, valueKey) {
  const p = resolve(__dirname, 'boards', file);
  if (!existsSync(p)) return [];
  const lines = readFileSync(p, 'utf8').trim().split('\n');
  const head = lines[0].split('\t');
  const rows = lines.slice(1).map((l) => Object.fromEntries(l.split('\t').map((v, i) => [head[i], v])));
  const best = new Map();
  for (const r of rows) {
    const valid = r.valid === '1';
    const val = valid ? parseFloat(r[valueKey]) : Infinity;
    const cur = best.get(r.stack);
    if (!cur || val < cur._v) best.set(r.stack, { ...r, _v: val, _valid: valid });
  }
  return [...best.values()].sort((a, b) => a._v - b._v);
}

const timeB = load('time.tsv', 'median_prove_s');
const memB = load('memory.tsv', 'peak_rss_MiB');

function table(entries, valueKey, unit, digits) {
  const base = entries.find((e) => e.stack === 'baseline');
  const baseV = base && base._valid ? base._v : null;
  let rank = 1;
  return entries.map((e) => {
    const valid = e._valid;
    const v = valid ? e._v.toFixed(digits) + ' ' + unit : 'INVALID';
    let vs = '—';
    if (valid && baseV != null) {
      const pct = (1 - e._v / baseV) * 100;
      vs = e.stack === 'baseline' ? 'baseline' : (pct >= 0 ? `${pct.toFixed(1)}% better` : `${(-pct).toFixed(1)}% worse`);
    }
    return { rank: valid ? rank++ : '—', stack: e.stack, value: v, vs, date: (e.iso || '').slice(0, 10) };
  });
}

const tRows = table(timeB, 'median_prove_s', 's', 2);
const mRows = table(memB, 'peak_rss_MiB', 'MiB', 0);

// ---- terminal ----
const pad = (s, n) => String(s).padEnd(n);
const padL = (s, n) => String(s).padStart(n);
function printT(title, rows) {
  console.log(`\n  ${title}\n`);
  if (!rows.length) { console.log('    (no runs yet)'); return; }
  console.log('  ' + [pad('#', 3), pad('prover', 24), padL('value', 14), padL('vs baseline', 14), pad('date', 10)].join(' '));
  console.log('  ' + '-'.repeat(70));
  for (const r of rows) console.log('  ' + [pad(r.rank, 3), pad(r.stack.slice(0, 24), 24), padL(r.value, 14), padL(r.vs, 14), pad(r.date, 10)].join(' '));
}
console.log('\n  ====== ZK PROVER ARENA — task hard2pow21 (2^21), frozen config, swap the prover ======');
printT('TIME BOARD (median prove seconds, single-thread, lower wins)', tRows);
printT('MEMORY BOARD (peak RSS MiB, lower wins)', mRows);
console.log('\n  Circuit, witness, proof system, and config are constants. The only variable is the prover.\n');

// ---- LEADERBOARD.md ----
if (writeMd) {
  const md = (rows, valueHead) => rows.length
    ? ['| # | prover | ' + valueHead + ' | vs baseline | date |', '|---|--------|------|-------------|------|',
       ...rows.map((r) => `| ${r.rank} | ${r.stack} | ${r.value} | ${r.vs} | ${r.date} |`)].join('\n')
    : '_(no runs yet)_';
  const out = `# Leaderboard — zk-prover-arena

**Task:** \`hard2pow21\` — prove the pinned 1,501,711-gate (2^21) circuit.
**Frozen:** circuit, witness, proof system (UltraHonk, poseidon2 oracle, ZK), single-threaded, native.
**Variable:** the prover implementation (\`bb\` binary rebuilt from modified barretenberg C++).
**Gates:** fresh random witness per run (emitted output must match — kills cached proofs); baseline \`bb verify\` against the pinned VK; cross-budgets (time entries: peak RSS <= 4096 MiB; memory entries: time <= 2x baseline — no trading one axis for the other); disk-ops cap (no spill); single-thread confirmed from bb's log.

Lower is better on both boards. Ranked by each stack's best valid run. Generated by \`node board.mjs --md\`.

## Time board (median prove seconds)

${md(tRows, 'median prove')}

## Memory board (peak RSS)

${md(mRows, 'peak RSS')}

_Numbers are comparable only when graded on the same machine — the canonical boards above are produced on the maintainer's grader (Apple M-series arm64, macOS). To get on the board: see "Submitting" in the README._
`;
  writeFileSync(resolve(__dirname, 'LEADERBOARD.md'), out);
  console.log('  wrote LEADERBOARD.md\n');
}
